sudo: required

services:
  - docker

language: generic

arch:
  - amd64
  - arm64

os: linux

script:
  - docker build -t moderras/pmcenter -f ./Dockerfile .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push moderras/pmcenter

## use standard notification to committer
#notifications:
#    recipients:
#      - "testautomatisierung@consol.de"
#    on_success: change # default: change
#    on_failure: always # default: always
