sudo: required

services:
  - docker

language: generic

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t moderras/pmcenter -f ./Dockerfile .
  - docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag moderras/pmcenter:latest .

## use standard notification to committer
#notifications:
#    recipients:
#      - "testautomatisierung@consol.de"
#    on_success: change # default: change
#    on_failure: always # default: always
